GET https://gary-phonebook-app.fly.dev/info

###
GET https://gary-phonebook-app.fly.dev/infssss

###
GET https://gary-phonebook-app.fly.dev/api/persons

###
GET https://gary-phonebook-app.fly.dev/api/persons/1

###
GET https://gary-phonebook-app.fly.dev/api/persons/10

###
GET https://gary-phonebook-app.fly.dev/api/persons/651d7c90e4850265874beb18

###
GET https://gary-phonebook-app.fly.dev/api/persons/651d7c90e4850265874beb17

###
DELETE https://gary-phonebook-app.fly.dev/api/persons/5

###
DELETE https://gary-phonebook-app.fly.dev/api/persons/651e2e0e16f9a42ba744345a

###
POST https://gary-phonebook-app.fly.dev/api/persons
Content-Type: application/json

{
    "name": "gg"
}

###
POST https://gary-phonebook-app.fly.dev/api/persons
Content-Type: application/json

{
    "number": 9999
}

###
POST https://gary-phonebook-app.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck", 
    "number": "12345"
}

###
PUT https://gary-phonebook-app.fly.dev/api/persons/651d847806e4f3d6ab2d1423
Content-Type: application/json

{
    "name": "Mary Poppendieck", 
    "number": "123-4565566"
}

